// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package gateway

import (
	"time"
)

type Address struct {
	ID      string
	Street  string
	City    string
	State   string
	Zip     string
	Country string
}

type Wishlist struct {
	ID          string
	Name        string
	Description string
	ShareCode   string
	Public      bool
}

type WishlistAddress struct {
	ID         string
	WishlistID string
}

type WishlistItem struct {
	ID          string
	WishlistID  string
	Link        string
	Name        string
	Description string
	ImageUrl    string
	Quantity    int64
	Price       int64
}

type WishlistPurchase struct {
	ID             string
	WishlistItemID string
	BuyerName      string
	Quantity       int64
	BoughtAt       time.Time
	BuyerEmail     string
	BuyerNotes     string
}
